# Generated by Django 5.2.10 on 2026-01-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquashPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SquashMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squash_matches_as_p1', to='squash.squashplayer')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squash_matches_as_p2', to='squash.squashplayer')),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
        migrations.CreateModel(
            name='SquashSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('player_1_points', models.IntegerField()),
                ('player_2_points', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='squash.squashmatch')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
