# Generated by Django 5.2.10 on 2026-02-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Squash session',
                'verbose_name_plural': 'Squash sessions',
                'ordering': ['-date_played'],
            },
        ),
        migrations.AlterModelOptions(
            name='squashmatch',
            options={'ordering': ['-date_played'], 'verbose_name': 'Squash match', 'verbose_name_plural': 'Squash matches'},
        ),
        migrations.AddField(
            model_name='squashmatch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='squash.squashsession'),
        ),
    ]
