# Generated by Django 5.2.10 on 2026-02-06 12:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squash', '0002_squashsession_alter_squashmatch_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='squashplayer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='squashplayer_name_ci_unique'),
        ),
    ]
