# Generated by Django 5.2.10 on 2026-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squash', '0003_squashplayer_squashplayer_name_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='squashmatch',
            name='set_type',
            field=models.CharField(choices=[('11', '11-point'), ('21', '21-point')], default='11', help_text='Point target for sets in this match (11 or 21)', max_length=2),
        ),
        migrations.AddField(
            model_name='squashset',
            name='is_incomplete',
            field=models.BooleanField(default=False, help_text="Automatically set if neither player reached the minimum score for the match's set type"),
        ),
    ]
