# Generated by Django 5.2.10 on 2026-04-14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SjoelenPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sjoelenplayer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='sjoelenplayer_name_ci_unique'),
        ),
    ]
