# Generated by Django 5.2.10 on 2026-04-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjoelen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SjoelenGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='SjoelenScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_1', models.IntegerField(blank=True, null=True)),
                ('round_2', models.IntegerField(blank=True, null=True)),
                ('round_3', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sjoelen.sjoelengame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sjoelen.sjoelenplayer')),
            ],
            options={
                'ordering': ['-game_id'],
            },
        ),
    ]
