# Generated by Django 5.2.10 on 2026-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_remove_yambscoresheet_row_1_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_1_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_2_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_3_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_4_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_5_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_6_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_c_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_fh_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_h_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_l_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_p_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yambscoresheet',
            name='row_s_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
